export enum EventoAlt {
  INICIO_SIMULACION,
  LLEGADA_PASAJERO,
  //BLOQUEO_LLEGADA,
  //BLOQUEO_CHEQUEO,
  //FIN_BLOQUEO_LLEGADA,
  //FIN_BLOQUEO_CHEQUEO,
  FIN_FACTURACION_VENTA_EMP_1,
  FIN_FACTURACION_VENTA_EMP_2,
  FIN_CHEQUEO_BILLETE,
  FIN_CONTROL_METALES,
  FIN_PASO_ENTRE_VENTA_FACTURACION_Y_CONTROL,
  FIN_PASO_ENTRE_CHEQUEO_Y_CONTROL,
  FIN_PASO_ENTRE_CONTROL_Y_EMBARQUE,
  FIN_SIMULACION
}